"""empty message

Revision ID: b3163533d98c
Revises: 
Create Date: 2023-05-04 20:08:53.352447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3163533d98c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efforts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effort_id', sa.String(length=128), nullable=False),
    sa.Column('effort_name', sa.String(length=128), nullable=False),
    sa.Column('athlete_username', sa.String(length=128), nullable=False),
    sa.Column('segment_name', sa.String(length=128), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('start_date_time', sa.DateTime(), nullable=False),
    sa.Column('elapsed_time', sa.Interval(), nullable=False),
    sa.Column('moving_time', sa.Interval(), nullable=False),
    sa.Column('effort_distance', sa.Float(), nullable=False),
    sa.Column('segment_distance', sa.Float(), nullable=False),
    sa.Column('average_watts', sa.Float(), nullable=False),
    sa.Column('average_heart_rate', sa.Float(), nullable=False),
    sa.Column('max_heart_rate', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effort_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('efforts')
    # ### end Alembic commands ###
